name : CI Pipeline

on: 
  push

jobs:
  run-test :
    runs-on : ubuntu@latest
  
    steps :
      - name : Checkout Code
        uses : actions/checkout@v4

      - name : Use Node.js
        uses : actions/setup-node@v4


      - name : Install Dependencies
        run : npm install 

        
        with :
          node-version : 18
  
